import AppKit
import Observation

@MainActor
@Observable
final class ClipboardManager {
    var items: [ClipboardItem] = []
    var isPaused: Bool = false
    var favoriteFolders: [FavoriteFolder] = []

    var maxHistoryCount: Int {
        didSet { UserDefaults.standard.set(maxHistoryCount, forKey: "maxHistoryCount") }
    }

    var maxTotalSizeMB: Int {
        didSet { UserDefaults.standard.set(maxTotalSizeMB, forKey: "maxTotalSizeMB") }
    }

    var excludedCategories: Set<ClipboardContentCategory> {
        didSet { UserDefaults.standard.set(excludedCategories.map(\.rawValue), forKey: "excludedCategories") }
    }

    /// 画像・PDF を OCR してテキスト認識するか（既定 true）。
    var ocrEnabled: Bool {
        didSet { UserDefaults.standard.set(ocrEnabled, forKey: "ocrEnabled") }
    }

    /// OCR 処理中のアイテム ID。起動時は空なので、中断されたOCRが「解析中…」のまま
    /// 固まることはない（nil = 未解析、このセットに含まれる = 解析中、で区別する）。
    private(set) var recognizingIds: Set<UUID> = []

    private(set) var isRestoringItem: Bool = false
    private var lastChangeCount: Int = 0
    private var pollingTimer: Timer?
    let store: ClipboardStore

    init() {
        store = ClipboardStore()
        maxHistoryCount = UserDefaults.standard.object(forKey: "maxHistoryCount") as? Int ?? 50
        maxTotalSizeMB = UserDefaults.standard.object(forKey: "maxTotalSizeMB") as? Int ?? 1024
        if let raw = UserDefaults.standard.stringArray(forKey: "excludedCategories") {
            excludedCategories = Set(raw.compactMap { ClipboardContentCategory(rawValue: $0) })
        } else {
            excludedCategories = []
        }
        ocrEnabled = UserDefaults.standard.object(forKey: "ocrEnabled") as? Bool ?? true
        items = store.loadIndex()
        favoriteFolders = store.loadFavoriteFolders()
        store.cleanupOrphans(validIDs: Set(items.map(\.id)))
        lastChangeCount = NSPasteboard.general.changeCount
        startPolling()
    }

    #if DEBUG
    /// スクリーンショット生成用: ポーリングせず、ストアは読み取り専用にして
    /// 実データへの書き込みを構造的に遮断する（View からの自動保存等が
    /// 発火しても実ファイルには一切触れない）
    init(previewItems: [ClipboardItem], previewFolders: [FavoriteFolder]) {
        store = ClipboardStore(isReadOnly: true)
        maxHistoryCount = 50
        maxTotalSizeMB = 1024
        excludedCategories = []
        ocrEnabled = false
        items = previewItems
        favoriteFolders = previewFolders
    }

    /// デモ録画モード（`--demo-mode`）用: デモデータを入れた状態でフル起動するが、
    /// ストアは読み取り専用にして実データへの書き込みを構造的に遮断する。
    /// ポーリングは動かすため録画中のライブのコピーも履歴に現れるが、read-only
    /// なので永続化されず実データには一切触れない。
    init(
        demoItems: [ClipboardItem],
        demoFolders: [FavoriteFolder],
        demoRepresentations: [UUID: [PasteboardRepresentation]]
    ) {
        store = ClipboardStore(isReadOnly: true, inMemoryRepresentations: demoRepresentations)
        maxHistoryCount = 50
        maxTotalSizeMB = 1024
        excludedCategories = []
        ocrEnabled = false
        items = demoItems
        favoriteFolders = demoFolders
        lastChangeCount = NSPasteboard.general.changeCount
        startPolling()
    }
    #endif

    // MARK: - Polling

    // タイマーはメインランループにスケジュールされるため、コールバックは常にメインスレッド。
    // アプリ終了時は applicationWillTerminate が stopPolling() を呼ぶ。
    func startPolling() {
        pollingTimer?.invalidate()
        pollingTimer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.checkForChanges()
            }
        }
    }

    func stopPolling() {
        pollingTimer?.invalidate()
        pollingTimer = nil
    }

    /// 履歴に記録しないペーストボードタイプ（http://nspasteboard.org/ の慣習 + 既知アプリ）。
    /// パスワードマネージャー等がこれらのタイプを付けてコピーした内容は取得しない。
    private static let ignoredPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",          // パスワード等の機密データ
        "org.nspasteboard.TransientType",          // 一時データ（履歴に残さない約束）
        "org.nspasteboard.AutoGeneratedType",      // 他のユーティリティが自動生成したデータ
        "com.agilebits.onepassword",               // 1Password（旧タイプ）
        "com.typeit4me.clipping",                  // TypeIt4Me
        "de.petermaurer.TransientPasteboardType",  // Keyboard Maestro 等
        "Pasteboard generator type",               // Nisus Writer 等
    ]

    private func checkForChanges() {
        guard !isPaused, !isRestoringItem else { return }

        let pasteboard = NSPasteboard.general
        let currentCount = pasteboard.changeCount
        guard currentCount != lastChangeCount else { return }
        lastChangeCount = currentCount

        // 機密・一時データは記録しない
        if let types = pasteboard.types,
           types.contains(where: { Self.ignoredPasteboardTypes.contains($0.rawValue) }) {
            return
        }

        guard let (newItem, representations) = ClipboardItem.capture(from: pasteboard) else { return }

        // Check excluded categories
        guard !excludedCategories.contains(newItem.category) else { return }

        addItem(newItem, representations: representations)
    }

    // MARK: - Item Management

    private func addItem(_ newItem: ClipboardItem, representations: [PasteboardRepresentation]) {
        // 保存済みアイテムの重複は除外しない
        let duplicateIDs = items.filter { !$0.isSaved && $0.hasSameContent(as: newItem) }.map(\.id)

        // Remove duplicates (unsaved only)
        items.removeAll { !$0.isSaved && $0.hasSameContent(as: newItem) }

        // Insert at front
        items.insert(newItem, at: 0)

        // Enforce count limit (unsaved only)
        var removedIDs = duplicateIDs
        let unsavedCount = items.filter({ !$0.isSaved }).count
        if unsavedCount > maxHistoryCount {
            var removeCount = unsavedCount - maxHistoryCount
            var i = items.count - 1
            while i >= 0, removeCount > 0 {
                if !items[i].isSaved {
                    removedIDs.append(items[i].id)
                    items.remove(at: i)
                    removeCount -= 1
                }
                i -= 1
            }
        }

        // Enforce total size limit (unsaved only)
        let maxBytes = maxTotalSizeMB * 1024 * 1024
        while items.filter({ !$0.isSaved }).count > 1, totalDataSize > maxBytes {
            if let lastUnsavedIndex = items.lastIndex(where: { !$0.isSaved }) {
                removedIDs.append(items[lastUnsavedIndex].id)
                items.remove(at: lastUnsavedIndex)
            } else {
                break
            }
        }

        // Save blobs first, then index
        store.saveBlobs(for: newItem.id, representations: representations, thumbnail: newItem.thumbnailData)
        store.saveIndex(items)
        if !removedIDs.isEmpty {
            store.deleteBlobs(for: removedIDs)
        }

        // 画像・PDF は非同期で OCR をかけ、認識テキストを後追いで反映する
        recognizeTextIfNeeded(for: newItem, representations: representations)
    }

    /// 画像・PDF クリップを Vision で OCR し、結果を recognizedText に反映する。
    /// ポーリングをブロックしないようバックグラウンドで実行する。
    private func recognizeTextIfNeeded(for item: ClipboardItem, representations: [PasteboardRepresentation]) {
        guard ocrEnabled, item.isOCRCandidate else { return }
        guard !store.isReadOnly else { return }

        let category = item.category
        let id = item.id
        // 認識に使う元データを抽出（フル解像度。サムネイルは小さすぎるので使わない）
        let imageData: Data? = representations.first(where: {
            let t = $0.typeRawValue
            return t == NSPasteboard.PasteboardType.tiff.rawValue
                || t == NSPasteboard.PasteboardType.png.rawValue
                || t == "public.jpeg" || t == "public.heic"
        })?.data
        let pdfData: Data? = representations.first(where: {
            $0.typeRawValue == NSPasteboard.PasteboardType.pdf.rawValue || $0.typeRawValue == "com.adobe.pdf"
        })?.data

        // 解析中マーカーを立てる（UI が「解析中…」を表示できるように）
        recognizingIds.insert(id)

        Task.detached(priority: .utility) {
            let text: String
            if category == .pdf, let pdfData {
                text = TextRecognizer.recognizeText(pdfData: pdfData)
            } else if let imageData {
                text = TextRecognizer.recognizeText(imageData: imageData)
            } else {
                text = ""
            }
            await MainActor.run { [weak self] in
                guard let self else { return }
                self.recognizingIds.remove(id)
                self.updateItem(id: id) { $0.recognizedText = text }
            }
        }
    }

    func removeItem(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        store.saveIndex(items)
        store.deleteBlobs(for: [item.id])
    }

    func removeAllItems() {
        // 保存済みアイテムは残す
        let saved = items.filter(\.isSaved)
        let removedIDs = items.filter { !$0.isSaved }.map(\.id)
        items = saved
        store.saveIndex(items)
        if !removedIDs.isEmpty {
            store.deleteBlobs(for: removedIDs)
        }
    }

    /// ID でアイテムを見つけて変更を適用し、index を保存する
    private func updateItem(id: UUID, _ mutate: (inout ClipboardItem) -> Void) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        mutate(&items[index])
        store.saveIndex(items)
    }

    /// 複数アイテムへ同じ変更を適用し、一度だけ index を保存する
    private func updateItems(ids: Set<UUID>, _ mutate: (inout ClipboardItem) -> Void) {
        var changed = false
        for index in items.indices where ids.contains(items[index].id) {
            mutate(&items[index])
            changed = true
        }
        if changed {
            store.saveIndex(items)
        }
    }

    // MARK: - Bulk Operations

    /// 複数アイテムをフォルダへ移動する（未保存のものはお気に入りに昇格）
    func moveItemsToFolder(itemIds: Set<UUID>, folderId: UUID?) {
        updateItems(ids: itemIds) {
            $0.isSaved = true
            $0.favoriteFolderId = folderId
        }
    }

    /// 複数アイテムをお気に入りに登録する（名前・フォルダは付けない）
    func favoriteItems(itemIds: Set<UUID>) {
        updateItems(ids: itemIds) {
            $0.isSaved = true
        }
    }

    /// 複数アイテムのお気に入りを解除する
    func unfavoriteItems(itemIds: Set<UUID>) {
        updateItems(ids: itemIds) {
            $0.isSaved = false
            $0.favoriteName = nil
            $0.favoriteFolderId = nil
        }
    }

    /// 複数アイテムを削除する
    func removeItems(itemIds: Set<UUID>) {
        guard !itemIds.isEmpty else { return }
        items.removeAll { itemIds.contains($0.id) }
        store.saveIndex(items)
        store.deleteBlobs(for: Array(itemIds))
    }

    // MARK: - Save (replaces Pin)

    func toggleSave(_ item: ClipboardItem) {
        updateItem(id: item.id) {
            $0.isSaved.toggle()
            if !$0.isSaved {
                $0.favoriteName = nil
                $0.favoriteFolderId = nil
            }
        }
    }

    // MARK: - Favorite

    func registerAsFavorite(_ item: ClipboardItem, name: String, folderId: UUID) {
        updateItem(id: item.id) {
            $0.isSaved = true
            $0.favoriteName = name
            $0.favoriteFolderId = folderId
        }
    }

    func removeFromFavorites(_ item: ClipboardItem) {
        updateItem(id: item.id) {
            $0.favoriteName = nil
            $0.favoriteFolderId = nil
        }
    }

    func updateFavoriteName(_ item: ClipboardItem, name: String) {
        updateItem(id: item.id) {
            $0.favoriteName = name.isEmpty ? nil : name
        }
    }

    func updateFavoriteFolder(_ item: ClipboardItem, folderId: UUID?) {
        updateItem(id: item.id) {
            $0.favoriteFolderId = folderId
        }
    }

    func updateFavoriteContent(_ item: ClipboardItem, text: String) {
        replaceContentWithPlainText(
            id: item.id,
            text: text,
            category: item.category,
            previewText: String(text.prefix(500)),
            thumbnailData: item.thumbnailData
        )
    }

    /// 複数アイテムをまとめてプレーンテキスト化する（変換可能なものだけ対象）。
    func convertItemsToPlainText(itemIds: Set<UUID>) {
        let targets = items.filter { itemIds.contains($0.id) && $0.canConvertToPlainText }
        for item in targets {
            convertToPlainText(item)
        }
    }

    func convertToPlainText(_ item: ClipboardItem) {
        // 画像・PDF は OCR 認識テキストを本文にする（previewText は "画像 800×600" 等のため）。
        // テキストが無い場合は変換しない（canConvertToPlainText でボタンも出ない）。
        let text: String
        if item.isOCRCandidate {
            guard let ocr = item.recognizedText, !ocr.isEmpty else { return }
            text = ocr
        } else {
            text = item.previewText
        }
        replaceContentWithPlainText(
            id: item.id,
            text: text,
            category: .plainText,
            previewText: String(text.prefix(500)),
            thumbnailData: nil
        )
    }

    private func replaceContentWithPlainText(
        id: UUID,
        text: String,
        category: ClipboardContentCategory,
        previewText: String,
        thumbnailData: Data?
    ) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        let (updated, rep) = items[index].replacingContentWithPlainText(
            text: text,
            category: category,
            previewText: previewText,
            thumbnailData: thumbnailData
        )
        items[index] = updated
        store.saveBlobs(for: id, representations: [rep], thumbnail: nil)
        store.saveIndex(items)
    }

    func createFavorite(text: String, name: String, folderId: UUID?) {
        insertPlainTextItem(ClipboardItem.plainText(
            text: text, isSaved: true, favoriteName: name, favoriteFolderId: folderId
        ))
    }

    func addTextToHistory(text: String) {
        insertPlainTextItem(ClipboardItem.plainText(text: text, isSaved: false))
    }

    private func insertPlainTextItem(_ pair: (item: ClipboardItem, representation: PasteboardRepresentation)) {
        items.insert(pair.item, at: 0)
        store.saveBlobs(for: pair.item.id, representations: [pair.representation], thumbnail: nil)
        store.saveIndex(items)
    }

    // MARK: - Favorite Folders

    /// 表示順（order 昇順）に並べたお気に入りフォルダ
    var sortedFavoriteFolders: [FavoriteFolder] {
        favoriteFolders.sorted { $0.order < $1.order }
    }

    func addFavoriteFolder(name: String) -> FavoriteFolder {
        let maxOrder = favoriteFolders.max(by: { $0.order < $1.order })?.order ?? -1
        let folder = FavoriteFolder(name: name, order: maxOrder + 1)
        favoriteFolders.append(folder)
        store.saveFavoriteFolders(favoriteFolders)
        return folder
    }

    func renameFavoriteFolder(id: UUID, name: String) {
        guard let index = favoriteFolders.firstIndex(where: { $0.id == id }) else { return }
        var updated = favoriteFolders
        updated[index].name = name
        favoriteFolders = updated
        store.saveFavoriteFolders(favoriteFolders)
    }

    func deleteFavoriteFolder(id: UUID) {
        favoriteFolders.removeAll { $0.id == id }
        store.saveFavoriteFolders(favoriteFolders)
        // 該当フォルダのアイテムからお気に入り属性をクリア（isSavedは維持）
        for i in items.indices where items[i].favoriteFolderId == id {
            items[i].favoriteName = nil
            items[i].favoriteFolderId = nil
        }
        store.saveIndex(items)
    }

    func reorderFavoriteFolders(_ folders: [FavoriteFolder]) {
        favoriteFolders = folders
        store.saveFavoriteFolders(favoriteFolders)
    }

    // MARK: - Restore

    func restoreToClipboard(_ item: ClipboardItem, asPlainText: Bool = false) {
        isRestoringItem = true

        // 履歴の再利用＝価値を感じたであろう操作。レビュー依頼の判断材料として記録する。
        ReviewRequest.recordValueMoment()

        if let reps = store.loadRepresentations(for: item.id) {
            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            if asPlainText {
                if let stringRep = reps.first(where: { $0.pasteboardType == .string }) {
                    pasteboard.declareTypes([.string], owner: nil)
                    pasteboard.setData(stringRep.data, forType: .string)
                } else if let ocr = item.recognizedText, !ocr.isEmpty {
                    // 画像など文字表現を持たないクリップは OCR 認識テキストを貼る
                    pasteboard.declareTypes([.string], owner: nil)
                    pasteboard.setData(Data(ocr.utf8), forType: .string)
                }
            } else {
                let types = reps.map(\.pasteboardType)
                pasteboard.declareTypes(types, owner: nil)
                for rep in reps {
                    pasteboard.setData(rep.data, forType: rep.pasteboardType)
                }
            }
        }
        lastChangeCount = NSPasteboard.general.changeCount

        // 使用したアイテムを先頭に移動（現在のイベント処理が終わってから行う）
        Task {
            if let index = items.firstIndex(where: { $0.id == item.id }) {
                let moved = items.remove(at: index)
                items.insert(moved, at: 0)
            }
            store.saveIndex(items)
        }

        // ポーリングが自分の書き込みを履歴として拾わないよう、復元直後の1サイクルは監視を止める
        Task {
            try? await Task.sleep(for: .milliseconds(500))
            isRestoringItem = false
        }
    }

    // MARK: - Statistics

    var totalDataSize: Int {
        items.reduce(0) { $0 + $1.totalDataSize }
    }

    var formattedTotalSize: String {
        totalDataSize.formatted(.byteCount(style: .file))
    }

    var categoryCountMap: [ClipboardContentCategory: Int] {
        var map: [ClipboardContentCategory: Int] = [:]
        for item in items {
            map[item.category, default: 0] += 1
        }
        return map
    }
}
